numSamples = 500;
combJitt = commsrc.combinedjitter(...
    'RandomJitter','on', ...
    'RandomStd',2e-4, ...
    'PeriodicJitter','on', ...
    'PeriodicAmplitude',5e-4, ...
    'PeriodicFrequencyHz',200)

y = generate(combJitt,numSamples);
x = [0:numSamples-1];

plot(x/combJitt.SamplingFrequency,y)
xlabel('时间 (s)')
ylabel('抖动 (s)')